apiVersion: apps/v1
kind: Deployment
metadata:
  name: cit270samuelservice
spec:
  replicas:
  selector:
    matchLabels:
      app: cit270samuelservice
  template:
    metadata:
      name: cit270samuelservice
      labels:
        app: cit270samuelservice
    spec:
      containers:
      - name: cit270samuelservice
        image: gcr.io/united-aviary-379820/samuel-api
        volumeMounts:
        - name: ssl
          mountPath: "/etc/letsencrypt/live/samuelkleine.cit270.com/"
        command: ["npm"]
        args: ["run", "start"]
        resources:
          requests:
            cpu: 0.125
            memory: 500Mi
          limits:
            cpu: 0.125
            memory: 600Mi
        imagePullPolicy: Always
      volumes: 
      - name: ssl
        secret:
          secretName: samuelcerts
---
apiVersion: v1
kind: Service
metadata:
  name: cit270samuelservice-loadbalancer
spec:
  selector:
    app: cit270samuelservice
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 443